[package]
authors    = [ "Nick Schipano <maverickn@gmail.com>" ]
edition    = "2018"
license    = "MIT"
name       = "web3-eth-event-parser"
version    = "0.1.0"

[dependencies]
parser = { path = "./parser" }
traits = { path = "./traits" }
